In [1]:
import numpy as np

In [4]:
data = [[1,2,3],
       [4,5,6],
       [7,8,9]]
for row in data:
    print(row)
    for col in row:
        print(col)

[1, 2, 3]
1
2
3
[4, 5, 6]
4
5
6
[7, 8, 9]
7
8
9


In [5]:
#enumerate return index no and its value
data = [[1,2,3],
       [4,5,6],
       [7,8,9]]
for row in enumerate(data):
    print(row)
    for col in enumerate(row):
        print(col)

(0, [1, 2, 3])
(0, 0)
(1, [1, 2, 3])
(1, [4, 5, 6])
(0, 1)
(1, [4, 5, 6])
(2, [7, 8, 9])
(0, 2)
(1, [7, 8, 9])


In [7]:
data = [[1,2,3],
       [4,5,6],
       [7,8,9]]
data[0][1] = 7
data

[[1, 7, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
data = [[1,2,3],
       [4,5,6],
       [7,8,9]]
for row_idx,row in enumerate(data):
    print(row_idx)
    for col_idx,col in enumerate(row):
        print(col_idx,end = ',')

0
0,1,2,1
0,1,2,2
0,1,2,

In [3]:
data = [[1,2,3],
       [4,5,6],
       [7,8,9]]
for row_idx,row in enumerate(data):
    for col_idx,col in enumerate(row):
        data[row_idx][col_idx] = data[row_idx][col_idx]+5
data

[[6, 7, 8], [9, 10, 11], [12, 13, 14]]

In [4]:
list(enumerate(['qasim','hamza','asif']))

[(0, 'qasim'), (1, 'hamza'), (2, 'asif')]

In [5]:
index,value = (0,'qasim')
print(index,value)

0 qasim


In [6]:
type(data)

list

# doing same thing with numpy

In [7]:
import numpy as np

In [8]:
data = np.array([[1,2,3],
       [4,5,6],
       [7,8,9]])
data+5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [9]:
type(data)

numpy.ndarray

In [20]:
data=np.arange(2*3*10*10).reshape(2,3,10,10)     #to know the dimension check open brackets
data[0] / 255                                    #coverting into grayscale

array([[[0.        , 0.00392157, 0.00784314, 0.01176471, 0.01568627,
         0.01960784, 0.02352941, 0.02745098, 0.03137255, 0.03529412],
        [0.03921569, 0.04313725, 0.04705882, 0.05098039, 0.05490196,
         0.05882353, 0.0627451 , 0.06666667, 0.07058824, 0.0745098 ],
        [0.07843137, 0.08235294, 0.08627451, 0.09019608, 0.09411765,
         0.09803922, 0.10196078, 0.10588235, 0.10980392, 0.11372549],
        [0.11764706, 0.12156863, 0.1254902 , 0.12941176, 0.13333333,
         0.1372549 , 0.14117647, 0.14509804, 0.14901961, 0.15294118],
        [0.15686275, 0.16078431, 0.16470588, 0.16862745, 0.17254902,
         0.17647059, 0.18039216, 0.18431373, 0.18823529, 0.19215686],
        [0.19607843, 0.2       , 0.20392157, 0.20784314, 0.21176471,
         0.21568627, 0.21960784, 0.22352941, 0.22745098, 0.23137255],
        [0.23529412, 0.23921569, 0.24313725, 0.24705882, 0.25098039,
         0.25490196, 0.25882353, 0.2627451 , 0.26666667, 0.27058824],
        [0.2745098 , 0.2784

# numpy basics

In [11]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
#printing table of 2
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [13]:
#another way to print table of 2
a = np.arange(2,21,2)    #last 2 is step size (start,stop,stepsize)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [15]:
a = np.array([[1,2,3],
       [4,5,6],
       [7,8,9]]  )    #object depend on methods and attributes      #rows ik dimension hai,rows k total index 3 hain
shape = print('shape',a.shape)    #each dimension number axis
dim = print('dimension',a.ndim)   #total dimension axis
size = print('size',a.size)    #total elements

shape (3, 3)
dimension 2
size 9


In [31]:
a = np.array([[1,2,3],
       [4,5,6]]  )    #object depend on methods and attributes      #rows ik dimension hai,rows k total index 3 hain
shape = print('shape',a.shape)    #each dimension number axis
dim = print('dimension',a.ndim)   #total dimension axis
size = print('size',a.size)    #total elements

shape (2, 3)
dimension 2
size 6


In [35]:
a = np.array([[1,2,3,10],
       [4,5,6,11],
       [7,8,9,12]]  ) 
a[1][2]
print('shape',a.shape)    #(3,4)---max 3 values including 0,1,2
a[1,2]
a[:,0]    #all rows of column 0

shape (3, 4)


array([1, 4, 7])

In [36]:
a = np.array([[1,2,3,10],
       [4,5,6,11],
       [7,8,9,12]]  ) 
a[:,-1]     #all rows of last column

array([10, 11, 12])

In [37]:
a = np.array([[1,2,3,10],
       [4,5,6,11],
       [7,8,9,12]]  ) 
a[1,:]   #all columns of index 1 row means 2nd row

array([ 4,  5,  6, 11])

# list

In [39]:
a = [[1,2,3,10],
       [4,5,6,11],
       [7,8,9,12]]


In [16]:
data = np.arange(10*10)  #100 values
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [48]:
data = np.arange(10*10).reshape(10,10)    #reshape(num_row,col_row)   #100 values,10 by 10 matrix
print(data)
#print(data[5: , 5:])
print(data[5,5])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
55


In [52]:
data = np.arange(11*11).reshape(11,11)
data

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

In [59]:
    #rows  #col
data[2:9 , 2:9]    # or [2:-2,2:-2]

array([[24, 25, 26, 27, 28, 29, 30],
       [35, 36, 37, 38, 39, 40, 41],
       [46, 47, 48, 49, 50, 51, 52],
       [57, 58, 59, 60, 61, 62, 63],
       [68, 69, 70, 71, 72, 73, 74],
       [79, 80, 81, 82, 83, 84, 85],
       [90, 91, 92, 93, 94, 95, 96]])

In [60]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [62]:
np.zeros(10,dtype = np.int)

C:\Users\FIVEST~1\AppData\Local\Temp/ipykernel_9916/3614971221.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros(10,dtype = np.int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [63]:
np.ones_like(data)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [64]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
np.empty_like(data)

array([[ -538840976,          40,  -596197616,          40,       65537,
           40108033,     5836890,     3146350,    73662567,   291111330,
           23337082],
       [  309068388,    23335514,   325845604,    90444634,     5706842,
             274030,   -25619099,       65537,   107216897,    23336026,
          376177252],
       [   23336538,   392954468,    23336794,   409731684,     5838938,
            3170414,   123994468,   426578796,   443357530,   460135002,
          476912474],
       [  493689946,   510467418,   527244890,   544022362,   560799834,
          577577306,   594354778,   611132250,   627909722,   644687194,
          661464666],
       [  678242138,   695019610,   711797082,       76378,   731910501,
          140771431,    27328930,     4653057,   174328164,   174325892,
           58928229],
       [    4664666,   207883108,   207880324,    58928485,     4664922,
          241438052,   241434756,    58928485,   342175578, -1267596912,
          2582

# 1-2,generate between 1 and 2, total equal steps 5

In [67]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [69]:
np.arange(1,2.25,0.25)   #ismy phr bhi calculations krna pari hain

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

# Sorting

In [17]:
d = np.array([8,4,2,3,1,6,9,5,7,10])
d

array([ 8,  4,  2,  3,  1,  6,  9,  5,  7, 10])

In [18]:
print("raw d values",d)
np.sort(d)

raw d values [ 8  4  2  3  1  6  9  5  7 10]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
list(enumerate([ 8 , 4,  2,  3,  1,  6,  9,  5,  7, 10]))

[(0, 8),
 (1, 4),
 (2, 2),
 (3, 3),
 (4, 1),
 (5, 6),
 (6, 9),
 (7, 5),
 (8, 7),
 (9, 10)]

In [21]:
print("raw d values",d)
np.argsort(d)    #gives the index in sorted manner

raw d values [ 8  4  2  3  1  6  9  5  7 10]


array([4, 2, 3, 1, 7, 5, 8, 0, 6, 9], dtype=int64)

In [22]:
d = np.array([8,4,2,3,1,6,9,5,7,10])
d.searchsorted(11)

10

In [23]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print("a",a)
print("b",b)
np.concatenate((a,b))

a [1 2 3 4]
b [5 6 7 8]


array([1, 2, 3, 4, 5, 6, 7, 8])